let hallo = 'Hello Winc Academy';
console.log(hallo);
let firstName = 'Sayma';
console.log(firstName);
const a = 4;
console.log(a + a);
console.log(a * 2);
console.log(a / 2);
console.log(a - 1);
console.log(a % 2);
console.log(-15 % 7);
console.log(a);
let age = 45;
console.log(typeof age);
age = '45';
console.log(typeof age);